name: DISW
version: '1.0'
main: net.bluept.DISW
author: 'pierrelasse'
commands:
  resetborder:
    description: Main command of the DISW plugin.
    permission: op
    permission-message: You need to be an operator to execute this command.
