main: net.bluept.DISW

name: DISW
version: '1.0'
author: 'pierrelasse'

commands:
  resetborder:
    description: Main command of the DISW plugin.
    permission: disw.resetborder
    permission-message: You need to be an operator to execute this command.

permissions:
  disw.resetborder: { default: op }
